export const CATALOG_SEARCH_REQUEST = 'CATALOG_SEARCH_REQUEST';
export const CATALOG_SEARCH_SUCCESS = 'CATALOG_SEARCH_SUCCESS';
export const CATALOG_SEARCH_FAILURE = 'CATALOG_SEARCH_FAILURE';

export const CATALOG_CATEGORY_MENU_REQUEST = 'CATALOG_CATEGORY_MENU_REQUEST';
export const CATALOG_CATEGORY_MENU_SUCCESS = 'CATALOG_CATEGORY_MENU_SUCCESS';
export const CATALOG_CATEGORY_MENU_FAILURE = 'CATALOG_CATEGORY_MENU_FAILURE';
export const CATALOG_CATEGORY_MENU_UPDATE = 'CATALOG_CATEGORY_MENU_UPDATE';
export const CATALOG_CATEGORY_MENU_TOGGLE = 'CATALOG_CATEGORY_MENU_TOGGLE';

export const CATALOG_CHILD_CATEGORY_MENU_UPDATE = 'CATALOG_CHILD_CATEGORY_MENU_UPDATE';

export const CATALOG_SEARCH_BRANDS_UPDATE = 'CATALOG_SEARCH_BRANDS_UPDATE';
export const CATALOG_SEARCH_POINTS_UPDATE = 'CATALOG_SEARCH_POINTS_UPDATE';
export const CATALOG_SEARCH_CATEGORIES_UPDATE = 'CATALOG_SEARCH_CATEGORIES_UPDATE';
export const CATALOG_SEARCH_RESULTS_UPDATE = 'CATALOG_SEARCH_RESULTS_UPDATE';
export const CATALOG_PAGE_NUMBER_UPDATE = 'CATALOG_PAGE_NUMBER_UPDATE';

export const CATALOG_SEARCH_FORM_UPDATE = 'CATALOG_SEARCH_FORM_UPDATE';
export const CATALOG_SHOW_ITEM = 'CATALOG_SHOW_ITEM';
export const CATALOG_CHECKBOX_UPDATE = 'CATALOG_CHECKBOX_UPDATE';
export const CATALOG_SEARCH_FORM_SUBMIT = 'CATALOG_SEARCH_FORM_SUBMIT';

export const CATALOG_CAROUSEL_ITEM_NUMBER_UPDATE = 'CATALOG_CAROUSEL_ITEM_NUMBER_UPDATE';
